name: Continous Integration

on: 
  push: 
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14.0-rc.2"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing uv
        run: pipx install uv

      - name: Installing dependencies
        run: uv sync

      - name: Running linters
        run: uv run task lint

      - name: Mypy checking
        run: uv run task mypy

  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14.0-rc.2"]
        os: [ubuntu, windows, macos]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing uv
        run: pipx install uv

      - name: Installing dependencies
        run: uv sync

      - name: Running tests with pytest
        run: uv run task test
